package mn.suld.plugin.hud;

import net.kyori.adventure.key.Key;

/**
 * GENERATED by tools/pack/gen_hud.py — do not edit. Glyphs of the resource-pack font {@code suld:hud}: the HUD panel,
 * the target frame, bar fill pieces, digit and text sets. Advances are exact (computed like the client does).
 */
public final class HudGlyphs {

    public static final Key FONT = Key.key("suld", "hud");

    /** A glyph and its advance in GUI pixels. */
    public record G(String ch, int advance) {
    }

    /** Symbols drawable in one set, the glyph for each and its advance. */
    public record CharSet(String symbols, String chars, int[] advances) {
        public int indexOf(char symbol) {
            return symbols.indexOf(symbol);
        }
    }

    private HudGlyphs() {
    }

    // layout (GUI px, x relative to the screen centre)
    public static final int BAR_W = 86;
    public static final int BAR_H = 8;
    public static final int SIDE_X = 4;
    public static final int DIAMOND_W = 30;
    public static final int PLAQUE_W = 14;
    public static final int SLOT_W = 12;
    public static final int TARGET_W = 182;

    public static final G NEG_1 = new G("\uE000", -1);
    public static final G POS_1 = new G("\uE001", 1);
    public static final G NEG_2 = new G("\uE002", -2);
    public static final G POS_2 = new G("\uE003", 2);
    public static final G NEG_4 = new G("\uE004", -4);
    public static final G POS_4 = new G("\uE005", 4);
    public static final G NEG_8 = new G("\uE006", -8);
    public static final G POS_8 = new G("\uE007", 8);
    public static final G NEG_16 = new G("\uE008", -16);
    public static final G POS_16 = new G("\uE009", 16);
    public static final G NEG_32 = new G("\uE00A", -32);
    public static final G POS_32 = new G("\uE00B", 32);
    public static final G NEG_64 = new G("\uE00C", -64);
    public static final G POS_64 = new G("\uE00D", 64);
    public static final G NEG_128 = new G("\uE00E", -128);
    public static final G POS_128 = new G("\uE00F", 128);
    public static final G FRAME_A_L = new G("\uE010", 87);
    public static final G FRAME_A_R = new G("\uE011", 87);
    public static final G FRAME_B_L = new G("\uE012", 87);
    public static final G FRAME_B_R = new G("\uE013", 87);
    public static final G FRAME_A_L_LOW = new G("\uE014", 87);
    public static final G FRAME_A_R_LOW = new G("\uE015", 87);
    public static final G DIAMOND = new G("\uE016", 31);
    public static final G PLAQUE = new G("\uE017", 15);
    public static final G TGT_FRAME = new G("\uE018", 183);
    public static final G TGT_FRAME_ELITE = new G("\uE019", 183);
    public static final G TGT_FRAME_BOSS = new G("\uE01A", 183);
    public static final G BI_A_HEART = new G("\uE07F", 7);
    public static final G BI_B_HEART = new G("\uE080", 7);
    public static final G BI_A_RES = new G("\uE081", 7);
    public static final G BI_B_RES = new G("\uE082", 7);
    public static final G BI_A_FOOD = new G("\uE083", 7);
    public static final G BI_B_FOOD = new G("\uE084", 7);
    public static final G BI_A_HORSE = new G("\uE085", 7);
    public static final G BI_B_HORSE = new G("\uE086", 7);
    public static final G BI_A_AIR = new G("\uE087", 7);
    public static final G BI_B_AIR = new G("\uE088", 7);
    public static final G BI_A_EXP = new G("\uE089", 7);
    public static final G BI_B_EXP = new G("\uE08A", 7);
    public static final G SLOT_READY = new G("\uE08B", 13);
    public static final G SLOT_CD = new G("\uE08C", 13);
    public static final G SLOT_LOCKED = new G("\uE08D", 13);
    public static final G SLOT_NORES = new G("\uE08E", 13);
    public static final G SLOT_ULT = new G("\uE08F", 13);
    public static final G NUM_I = new G("\uE090", 3);
    public static final G NUM_II = new G("\uE091", 5);
    public static final G NUM_III = new G("\uE092", 7);
    public static final G NUM_IV = new G("\uE093", 7);
    public static final G NUM_ULT = new G("\uE094", 7);
    public static final G NUM_LOCK = new G("\uE095", 7);
    public static final G ICON_SPEED = new G("\uE096", 10);
    public static final G ICON_SLOW = new G("\uE097", 10);
    public static final G ICON_STRENGTH = new G("\uE098", 10);
    public static final G ICON_WEAKNESS = new G("\uE099", 10);
    public static final G ICON_POISON = new G("\uE09A", 10);
    public static final G ICON_REGEN = new G("\uE09B", 10);
    public static final G ICON_FIRE = new G("\uE09C", 10);
    public static final G ICON_WITHER = new G("\uE09D", 10);
    public static final G ICON_SHIELD = new G("\uE09E", 10);
    public static final G ICON_EMPOWER = new G("\uE09F", 10);
    public static final G ICON_SOUL = new G("\uE0A0", 10);
    public static final G ICON_DANGER = new G("\uE0A1", 10);
    public static final G ICON_SAFE = new G("\uE0A2", 10);
    public static final G ICON_BROKEN = new G("\uE0A3", 10);
    public static final G ICON_WOUND = new G("\uE0A4", 10);
    public static final G ICON_RELIC = new G("\uE0A5", 10);
    public static final G ICON_RESIST = new G("\uE0A6", 10);
    public static final G ICON_HUNGER = new G("\uE0A7", 10);
    public static final G ICON_JUMP = new G("\uE0A8", 10);
    public static final G ICON_NIGHT = new G("\uE0A9", 10);
    public static final G ICON_HASTE = new G("\uE0AA", 10);

    /** fill pieces of widths [1, 2, 4, 8, 16, 32, 64] */
    public static final G[] FILL_HP = {new G("\uE01B", 2), new G("\uE01C", 3), new G("\uE01D", 5), new G("\uE01E", 9), new G("\uE01F", 17), new G("\uE020", 33), new G("\uE021", 65)};
    /** fill pieces of widths [1, 2, 4, 8, 16, 32, 64] */
    public static final G[] FILL_HP_CHIP = {new G("\uE022", 2), new G("\uE023", 3), new G("\uE024", 5), new G("\uE025", 9), new G("\uE026", 17), new G("\uE027", 33), new G("\uE028", 65)};
    /** fill pieces of widths [1, 2, 4, 8, 16, 32, 64] */
    public static final G[] FILL_ABSORB = {new G("\uE029", 2), new G("\uE02A", 3), new G("\uE02B", 5), new G("\uE02C", 9), new G("\uE02D", 17), new G("\uE02E", 33), new G("\uE02F", 65)};
    /** fill pieces of widths [1, 2, 4, 8, 16, 32, 64] */
    public static final G[] FILL_RES_BAATAR = {new G("\uE030", 2), new G("\uE031", 3), new G("\uE032", 5), new G("\uE033", 9), new G("\uE034", 17), new G("\uE035", 33), new G("\uE036", 65)};
    /** fill pieces of widths [1, 2, 4, 8, 16, 32, 64] */
    public static final G[] FILL_RES_MERGEN = {new G("\uE037", 2), new G("\uE038", 3), new G("\uE039", 5), new G("\uE03A", 9), new G("\uE03B", 17), new G("\uE03C", 33), new G("\uE03D", 65)};
    /** fill pieces of widths [1, 2, 4, 8, 16, 32, 64] */
    public static final G[] FILL_RES_BOO = {new G("\uE03E", 2), new G("\uE03F", 3), new G("\uE040", 5), new G("\uE041", 9), new G("\uE042", 17), new G("\uE043", 33), new G("\uE044", 65)};
    /** fill pieces of widths [1, 2, 4, 8, 16, 32, 64] */
    public static final G[] FILL_RES_DARKHAN = {new G("\uE045", 2), new G("\uE046", 3), new G("\uE047", 5), new G("\uE048", 9), new G("\uE049", 17), new G("\uE04A", 33), new G("\uE04B", 65)};
    /** fill pieces of widths [1, 2, 4, 8, 16, 32, 64] */
    public static final G[] FILL_RES_KHULEGCHIN = {new G("\uE04C", 2), new G("\uE04D", 3), new G("\uE04E", 5), new G("\uE04F", 9), new G("\uE050", 17), new G("\uE051", 33), new G("\uE052", 65)};
    /** fill pieces of widths [1, 2, 4, 8, 16, 32, 64] */
    public static final G[] FILL_FOOD = {new G("\uE053", 2), new G("\uE054", 3), new G("\uE055", 5), new G("\uE056", 9), new G("\uE057", 17), new G("\uE058", 33), new G("\uE059", 65)};
    /** fill pieces of widths [1, 2, 4, 8, 16, 32, 64] */
    public static final G[] FILL_AIR = {new G("\uE05A", 2), new G("\uE05B", 3), new G("\uE05C", 5), new G("\uE05D", 9), new G("\uE05E", 17), new G("\uE05F", 33), new G("\uE060", 65)};
    /** fill pieces of widths [1, 2, 4, 8, 16, 32, 64] */
    public static final G[] FILL_MOUNT = {new G("\uE061", 2), new G("\uE062", 3), new G("\uE063", 5), new G("\uE064", 9), new G("\uE065", 17), new G("\uE066", 33), new G("\uE067", 65)};
    /** fill pieces of widths [1, 2, 4, 8, 16, 32, 64] */
    public static final G[] FILL_EXP = {new G("\uE068", 2), new G("\uE069", 3), new G("\uE06A", 5), new G("\uE06B", 9), new G("\uE06C", 17), new G("\uE06D", 33), new G("\uE06E", 65)};
    /** fill pieces of widths [1, 2, 4, 8, 16, 32, 64, 128] */
    public static final G[] FILL_TGT = {new G("\uE06F", 2), new G("\uE070", 3), new G("\uE071", 5), new G("\uE072", 9), new G("\uE073", 17), new G("\uE074", 33), new G("\uE075", 65), new G("\uE076", 129)};
    /** fill pieces of widths [1, 2, 4, 8, 16, 32, 64, 128] */
    public static final G[] FILL_TGT_CHIP = {new G("\uE077", 2), new G("\uE078", 3), new G("\uE079", 5), new G("\uE07A", 9), new G("\uE07B", 17), new G("\uE07C", 33), new G("\uE07D", 65), new G("\uE07E", 129)};

    public static final CharSet ROW_A = new CharSet("0123456789/%.+-ksxMAX", "\uE0AB\uE0AC\uE0AD\uE0AE\uE0AF\uE0B0\uE0B1\uE0B2\uE0B3\uE0B4\uE0B5\uE0B6\uE0B7\uE0B8\uE0B9\uE0BA\uE0BB\uE0BC\uE0BD\uE0BE\uE0BF", new int[]{5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 5, 5, 5, 5, 5, 5, 5, 5});
    public static final CharSet ROW_B = new CharSet("0123456789/%.+-ksxMAX", "\uE0C0\uE0C1\uE0C2\uE0C3\uE0C4\uE0C5\uE0C6\uE0C7\uE0C8\uE0C9\uE0CA\uE0CB\uE0CC\uE0CD\uE0CE\uE0CF\uE0D0\uE0D1\uE0D2\uE0D3\uE0D4", new int[]{5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 5, 5, 5, 5, 5, 5, 5, 5});
    public static final CharSet SLOT = new CharSet("0123456789/%.+-ksxMAX", "\uE0D5\uE0D6\uE0D7\uE0D8\uE0D9\uE0DA\uE0DB\uE0DC\uE0DD\uE0DE\uE0DF\uE0E0\uE0E1\uE0E2\uE0E3\uE0E4\uE0E5\uE0E6\uE0E7\uE0E8\uE0E9", new int[]{5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 5, 5, 5, 5, 5, 5, 5, 5});
    public static final CharSet BUFF = new CharSet("0123456789/%.+-ksxMAX", "\uE0EA\uE0EB\uE0EC\uE0ED\uE0EE\uE0EF\uE0F0\uE0F1\uE0F2\uE0F3\uE0F4\uE0F5\uE0F6\uE0F7\uE0F8\uE0F9\uE0FA\uE0FB\uE0FC\uE0FD\uE0FE", new int[]{5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 5, 5, 5, 5, 5, 5, 5, 5});
    public static final CharSet TARGET = new CharSet("0123456789/%.+-ksxMAX", "\uE0FF\uE100\uE101\uE102\uE103\uE104\uE105\uE106\uE107\uE108\uE109\uE10A\uE10B\uE10C\uE10D\uE10E\uE10F\uE110\uE111\uE112\uE113", new int[]{5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 5, 5, 5, 5, 5, 5, 5, 5});
    public static final CharSet LINE = new CharSet(" \u0410\u0411\u0412\u0413\u0414\u0415\u0401\u0416\u0417\u0418\u0419\u041A\u041B\u041C\u041D\u041E\u04E8\u041F\u0420\u0421\u0422\u0423\u04AE\u0424\u0425\u0426\u0427\u0428\u042B\u042C\u042D\u042E\u042FSU\u00DCLDVINRGFW0123456789+-.!?/:\u00B7ABCEHKMOPTXY\u0429\u042AJQZ,'()%_=<>\u2014\u20AE\u25C6\u2726\u2714\u2716\u279C\u2665\u2694\u2605\u2744#&;\"", "\uE114\uE115\uE116\uE117\uE118\uE119\uE11A\uE11B\uE11C\uE11D\uE11E\uE11F\uE120\uE121\uE122\uE123\uE124\uE125\uE126\uE127\uE128\uE129\uE12A\uE12B\uE12C\uE12D\uE12E\uE12F\uE130\uE131\uE132\uE133\uE134\uE135\uE136\uE137\uE138\uE139\uE13A\uE13B\uE13C\uE13D\uE13E\uE13F\uE140\uE141\uE142\uE143\uE144\uE145\uE146\uE147\uE148\uE149\uE14A\uE14B\uE14C\uE14D\uE14E\uE14F\uE150\uE151\uE152\uE153\uE154\uE155\uE156\uE157\uE158\uE159\uE15A\uE15B\uE15C\uE15D\uE15E\uE15F\uE160\uE161\uE162\uE163\uE164\uE165\uE166\uE167\uE168\uE169\uE16A\uE16B\uE16C\uE16D\uE16E\uE16F\uE170\uE171\uE172\uE173\uE174\uE175\uE176\uE177\uE178\uE179\uE17A\uE17B\uE17C", new int[]{4, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 5, 7, 7, 7, 7, 7, 7, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 6, 3, 3, 7, 7, 3, 3, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 4, 3, 4, 4, 7, 7, 7, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 4, 5});
    public static final CharSet LEVEL = new CharSet("0123456789", "\uE17D\uE17E\uE17F\uE180\uE181\uE182\uE183\uE184\uE185\uE186", new int[]{7, 6, 7, 7, 7, 7, 7, 7, 7, 7});
}
