# Generated by SULD deploy.sh on first install; edit freely afterwards (never overwritten).
server-port=@SERVER_PORT@
motd=@MOTD@
max-players=@MAX_PLAYERS@
online-mode=@ONLINE_MODE@
# SULD ships its own hardcore/death system; vanilla hardcore stays off.
hardcore=false
difficulty=hard
pvp=true
spawn-protection=0
view-distance=8
simulation-distance=6
enable-command-block=false
enable-rcon=false
enable-query=false
white-list=false
enforce-secure-profile=true
network-compression-threshold=256
sync-chunk-writes=true
