package mn.suld.plugin.ui;

import net.kyori.adventure.key.Key;

/**
 * GENERATED by tools/pack/gen_ui.py — do not edit. Code points of the glyphs in the resource-pack font
 * {@code suld:ui} (logo, icons, rank badges, GUI backgrounds, space shifts).
 */
public final class Glyphs {

    public static final Key FONT = Key.key("suld", "ui");

    /** advance -1 */
    public static final String NEG_1 = "\uE000";
    /** advance +1 */
    public static final String POS_1 = "\uE001";
    /** advance -2 */
    public static final String NEG_2 = "\uE002";
    /** advance +2 */
    public static final String POS_2 = "\uE003";
    /** advance -4 */
    public static final String NEG_4 = "\uE004";
    /** advance +4 */
    public static final String POS_4 = "\uE005";
    /** advance -8 */
    public static final String NEG_8 = "\uE006";
    /** advance +8 */
    public static final String POS_8 = "\uE007";
    /** advance -16 */
    public static final String NEG_16 = "\uE008";
    /** advance +16 */
    public static final String POS_16 = "\uE009";
    /** advance -32 */
    public static final String NEG_32 = "\uE00A";
    /** advance +32 */
    public static final String POS_32 = "\uE00B";
    /** advance -64 */
    public static final String NEG_64 = "\uE00C";
    /** advance +64 */
    public static final String POS_64 = "\uE00D";
    /** advance -128 */
    public static final String NEG_128 = "\uE00E";
    /** advance +128 */
    public static final String POS_128 = "\uE00F";
    /** SÜLD logo 60x40: the emblem over the letters (5 chat lines tall) */
    public static final String LOGO = "\uE010";
    /** 8x8 icon heart */
    public static final String ICON_HEART = "\uE011";
    /** 8x8 icon coin */
    public static final String ICON_COIN = "\uE012";
    /** 8x8 icon star */
    public static final String ICON_STAR = "\uE013";
    /** 8x8 icon exp */
    public static final String ICON_EXP = "\uE014";
    /** 8x8 icon scroll */
    public static final String ICON_SCROLL = "\uE015";
    /** 8x8 icon shield */
    public static final String ICON_SHIELD = "\uE016";
    /** 8x8 icon flag */
    public static final String ICON_FLAG = "\uE017";
    /** 8x8 icon pin */
    public static final String ICON_PIN = "\uE018";
    /** 8x8 icon person */
    public static final String ICON_PERSON = "\uE019";
    /** 8x8 icon sword */
    public static final String ICON_SWORD = "\uE01A";
    /** 8x8 icon ulzii */
    public static final String ICON_ULZII = "\uE01B";
    /** 8x8 icon skull */
    public static final String ICON_SKULL = "\uE01C";
    /** 8x8 icon clock */
    public static final String ICON_CLOCK = "\uE01D";
    /** 8x8 icon signal */
    public static final String ICON_SIGNAL = "\uE01E";
    /** badge «АРД» */
    public static final String BADGE_RANK_ARD = "\uE01F";
    /** badge «ЦЭРЭГ» */
    public static final String BADGE_RANK_TSEREG = "\uE020";
    /** badge «АРАВТ» */
    public static final String BADGE_RANK_ARAVT = "\uE021";
    /** badge «ЗУУТ» */
    public static final String BADGE_RANK_ZUUT = "\uE022";
    /** badge «МЯНГАТ» */
    public static final String BADGE_RANK_MYANGAT = "\uE023";
    /** badge «ТҮМЭН» */
    public static final String BADGE_RANK_TUMEN = "\uE024";
    /** badge «НОЁН» */
    public static final String BADGE_RANK_NOYON = "\uE025";
    /** badge «ХААН» */
    public static final String BADGE_RANK_KHAAN = "\uE026";
    /** badge «ЭЗЭН» */
    public static final String BADGE_STAFF_OWNER = "\uE027";
    /** badge «АДМИН» */
    public static final String BADGE_STAFF_ADMIN = "\uE028";
    /** badge «DEV» */
    public static final String BADGE_STAFF_DEVELOPER = "\uE029";
    /** badge «МОД» */
    public static final String BADGE_STAFF_MOD = "\uE02A";
    /** badge «ТУСЛАГЧ» */
    public static final String BADGE_STAFF_HELPER = "\uE02B";
    /** badge «СТРИМЕР» */
    public static final String BADGE_STAFF_STREAMER = "\uE02C";
    /** badge «ДЭМЖИГЧ» */
    public static final String BADGE_STAFF_SPONSOR = "\uE02D";
    /** badge «БААТАР» */
    public static final String BADGE_CLASS_BAATAR = "\uE02E";
    /** badge «МЭРГЭН» */
    public static final String BADGE_CLASS_MERGEN = "\uE02F";
    /** badge «БӨӨ» */
    public static final String BADGE_CLASS_BOO = "\uE030";
    /** badge «ДАРХАН» */
    public static final String BADGE_CLASS_DARKHAN = "\uE031";
    /** badge «ХҮЛЭГЧИН» */
    public static final String BADGE_CLASS_KHULEGCHIN = "\uE032";
    /** badge «ОВОГ» */
    public static final String BADGE_CLAN = "\uE033";
    /** badge «АЮУЛГҮЙ» */
    public static final String BADGE_SAFE = "\uE034";
    /** badge «АЮУЛТАЙ» */
    public static final String BADGE_DANGER = "\uE035";
    /** chest background main 176x126 */
    public static final String GUI_MAIN = "\uE036";
    /** chest background welcome 176x72 */
    public static final String GUI_WELCOME = "\uE037";
    /** chest background cosmetics 176x126 (4x2 cards) */
    public static final String GUI_COSMETICS = "\uE038";
    /** chest background frame 176x126 (framed slots) */
    public static final String GUI_FRAME = "\uE039";
    /** chest background skillmap 176x126 (parchment map, toolbar row) */
    public static final String GUI_SKILLMAP = "\uE03A";
    /** chest background dungeons 176x126 (dungeon ladder) */
    public static final String GUI_DUNGEONS = "\uE03B";
    /** chest background quests 176x126 (story map) */
    public static final String GUI_QUESTS = "\uE03C";

    private Glyphs() {
    }
}
