#!/usr/bin/env python3
"""Turn the JSON the in-game combat verification suite writes (plugins/SULD/qa/skill-qa-*.json, produced by
`/skillsadmin qa <player> [suite...]`) into the markdown report docs/SKILL_TREE_COMBAT_VERIFICATION.md.

    python3 tools/validation/skill_qa_report.py RESULT.json [RESULT2.json ...] > docs/SKILL_TREE_COMBAT_VERIFICATION.md

Several result files (one per suite run) are merged; a later file replaces an earlier result with the same id.
"""
import json
import sys
from collections import OrderedDict

CATS = OrderedDict([
    ("stat", "Stat nodes"),
    ("mod", "Spell modifiers"),
    ("proc", "Passive spells"),
    ("wiring", "Passive-spell triggers on real game events"),
    ("keystone", "Keystones"),
    ("ultimate", "Ultimates"),
    ("cooldown", "Cooldowns"),
    ("harness", "Harness errors"),
])


def fmt(v):
    if isinstance(v, float) and v == int(v) and abs(v) < 1e9:
        return str(int(v))
    return str(v)


def main(paths):
    merged = OrderedDict()
    generated = []
    for p in paths:
        d = json.load(open(p, encoding="utf-8"))
        generated.append(d["generated"])
        for r in d["results"]:
            merged[r["id"]] = r
    results = list(merged.values())
    total = len(results)
    counts = {k: sum(1 for r in results if r["verdict"] == k) for k in ("PASS", "FAIL", "NOT_MEASURABLE")}
    out = ["# SÜLD skill tree — combat verification report", "",
           "Generated by `tools/validation/skill_qa_report.py` from the in-game suite (`/skillsadmin qa`), run on a real Paper 1.21.11 server.",
           "Each row is one effect of one node: the measured game value **before** the node is learned, **after** it is learned, and what the",
           "data file promises. A row passes only when the measured change matches within the stated tolerance. Statistical rows",
           "(crit, dodge, proc chance, loot, durability, echo) use enough trials that the tolerance is four standard deviations.", "",
           f"Runs: {', '.join(generated)}", "",
           f"**{total} checks: {counts['PASS']} pass, {counts['FAIL']} fail, {counts['NOT_MEASURABLE']} not measurable.**", ""]
    for cat, title in CATS.items():
        rows = [r for r in results if r["category"] == cat]
        if not rows:
            continue
        p = sum(1 for r in rows if r["verdict"] == "PASS")
        out += [f"## {title} ({p}/{len(rows)} pass)", "", "| result | check | measured | before | after | expected | note |", "|---|---|---|---|---|---|---|"]
        for r in rows:
            mark = {"PASS": "PASS", "FAIL": "**FAIL**", "NOT_MEASURABLE": "n/a"}[r["verdict"]]
            out.append("| {} | `{}` {} | {} | {} | {} | {} | {} |".format(
                mark, r["id"], r["what"].replace("|", "/"), r["metric"].replace("|", "/"), fmt(r["before"]), fmt(r["after"]),
                r["expected"].replace("|", "/"), r["note"].replace("|", "/")))
        out.append("")
    fails = [r for r in results if r["verdict"] == "FAIL"]
    if fails:
        out += ["## Failures", ""] + [f"* `{r['id']}` — {r['what']}: {r['metric']} {fmt(r['before'])} → {fmt(r['after'])}, expected {r['expected']} {r['note']}" for r in fails] + [""]
    nm = [r for r in results if r["verdict"] == "NOT_MEASURABLE"]
    if nm:
        out += ["## Not measurable here", ""] + [f"* `{r['id']}` — {r['what']}: {r['note']}" for r in nm] + [""]
    print("\n".join(out))


if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    main(sys.argv[1:])
