package mn.suld.api.item;

import org.jetbrains.annotations.NotNull;

import java.util.Locale;
import java.util.Optional;

/**
 * Item rarity tiers. Colour and name are the least of it — every tier changes how an item is made and used:
 *
 * <ul>
 *   <li><b>affixes</b>: how many random affixes a generated item rolls (none for common, five for mythic);</li>
 *   <li><b>stat multiplier</b>: base stats scale with it, relative to the item's own lowest rarity;</li>
 *   <li><b>roll floor</b>: affixes and base stats roll in the upper part of their range on higher tiers;</li>
 *   <li><b>durability</b>: maximum durability multiplier (unique relics never wear);</li>
 *   <li><b>sell / salvage</b>: coin value and salvage material yield;</li>
 *   <li><b>binding</b>: legendary binds when equipped, ancient and above when picked up;</li>
 *   <li><b>announce</b>: legendary and above are announced to the server when they drop.</li>
 * </ul>
 *
 * {@link #UNIQUE} items exist once on the whole server; they are never generated by loot (the relic system mints them).
 */
public enum ItemRarity {
    COMMON("common", "Энгийн", "#9d9d9d", 1000, 0, 0, 1.00, 0.00, 1.0, 1, 1),
    UNCOMMON("uncommon", "Ховор", "#1eff00", 400, 1, 1, 1.10, 0.00, 1.2, 2, 1),
    RARE("rare", "Нандин", "#0070dd", 160, 2, 2, 1.25, 0.10, 1.5, 5, 2),
    EPIC("epic", "Домогт", "#a335ee", 60, 3, 3, 1.40, 0.25, 1.8, 12, 3),
    LEGENDARY("legendary", "Алдарт", "#ff8000", 18, 4, 4, 1.60, 0.40, 2.2, 30, 5),
    ANCIENT("ancient", "Эртний", "#e6cc80", 5, 4, 5, 1.80, 0.55, 2.6, 60, 7),
    MYTHIC("mythic", "Домгийн", "#ff4040", 1, 5, 5, 2.00, 0.70, 3.0, 120, 10),
    /** One-of-a-kind on the entire server; never randomly dropped. */
    UNIQUE("unique", "Цор ганц", "#00ffd0", 0, 0, 0, 2.00, 1.00, 0, 0, 0);

    private final String id;
    private final String displayName;
    private final String colorHex;
    private final int defaultWeight;
    private final int minAffixes;
    private final int maxAffixes;
    private final double statMultiplier;
    private final double rollFloor;
    private final double durabilityMultiplier;
    private final int sellMultiplier;
    private final int salvageYield;

    ItemRarity(String id, String displayName, String colorHex, int defaultWeight, int minAffixes, int maxAffixes,
               double statMultiplier, double rollFloor, double durabilityMultiplier, int sellMultiplier, int salvageYield) {
        this.id = id;
        this.displayName = displayName;
        this.colorHex = colorHex;
        this.defaultWeight = defaultWeight;
        this.minAffixes = minAffixes;
        this.maxAffixes = maxAffixes;
        this.statMultiplier = statMultiplier;
        this.rollFloor = rollFloor;
        this.durabilityMultiplier = durabilityMultiplier;
        this.sellMultiplier = sellMultiplier;
        this.salvageYield = salvageYield;
    }

    public @NotNull String id() {
        return id;
    }

    public @NotNull String displayName() {
        return displayName;
    }

    /** Hex colour (e.g. {@code #ff8000}) for text/UI tinting. */
    public @NotNull String colorHex() {
        return colorHex;
    }

    /** Default relative drop weight; {@code 0} means never rolled randomly. */
    public int defaultWeight() {
        return defaultWeight;
    }

    public int minAffixes() {
        return minAffixes;
    }

    public int maxAffixes() {
        return maxAffixes;
    }

    /** Multiplier on the definition's base stats. */
    public double statMultiplier() {
        return statMultiplier;
    }

    /** Rolls land in [floor, 1] of their range (0 = anywhere). */
    public double rollFloor() {
        return rollFloor;
    }

    /** Multiplier on the definition's durability; 0 = never wears. */
    public double durabilityMultiplier() {
        return durabilityMultiplier;
    }

    public int sellMultiplier() {
        return sellMultiplier;
    }

    /** Salvage materials per item (before the level bonus). */
    public int salvageYield() {
        return salvageYield;
    }

    /** Binding this rarity forces regardless of the definition. */
    public Binding forcedBinding() {
        return switch (this) {
            case LEGENDARY -> Binding.ON_EQUIP;
            case ANCIENT, MYTHIC -> Binding.ON_PICKUP;
            case UNIQUE -> Binding.SOULBOUND;
            default -> Binding.NONE;
        };
    }

    /** Dropping one is announced to the whole server. */
    public boolean announced() {
        return ordinal() >= LEGENDARY.ordinal() && this != UNIQUE;
    }

    /** Whether items of this rarity must be unique across the whole server. */
    public boolean isServerUnique() {
        return this == UNIQUE;
    }

    public boolean atLeast(ItemRarity other) {
        return ordinal() >= other.ordinal();
    }

    public static @NotNull Optional<ItemRarity> byId(String id) {
        if (id == null) {
            return Optional.empty();
        }
        String needle = id.trim().toLowerCase(Locale.ROOT);
        for (ItemRarity value : values()) {
            if (value.id.equals(needle)) {
                return Optional.of(value);
            }
        }
        return Optional.empty();
    }
}
